### PR TITLE
Update RB community notebooks

### PR DESCRIPTION
**Pull request by ShellyGarion**
### Summary
- Update RB community tutorial with new API
- Added a new tutorial on advanced RB methods (interleaved and purity RB)
- Update readme with QV tutorial and advanced RB tutorial

### Details and comments
https://github.com/Qiskit/qiskit-ignis/issues/221

### CODE REVIEW

**Comment by ShellyGarion** [comment]
@dcmckayibm - please approve.

**Comment by ShellyGarion** [comment]
@dcmckayibm - please approve the tutorial on advanced RB methods (interleaved and purity RB)

**Comment by dcmckayibm** [comment]
Looks good, I'm getting some latex rendering errors in the "definition of purity" section

**Comment by ShellyGarion** [comment]
I fixed the latex issues.

**Pull request merged**
